Repository cognizone/asquare, pull requests merged in 2022-09, with the labels that each got.

#146 fix #145 doing indexing in configurable blocks
  cube/src/main/java/zone/cogni/asquare/cube/index/IndexFolderUriReport.java
  cube/src/main/java/zone/cogni/asquare/cube/index/StaticIndexIndexingService.java
Labels: enhancement

#147 fix: add namespace when namespace not present
  cube/src/main/java/zone/cogni/asquare/cube/convertor/data2shacl/ShaclGenerator.java
Labels: improvement

#151 fix issues #149 and #150 i.e. performance improvement of indexing and…
  cube/src/main/java/zone/cogni/asquare/cube/index/AliasedCollectionIndexingService.java
  cube/src/main/java/zone/cogni/asquare/cube/index/AliasedIndexIndexingService.java
  cube/src/main/java/zone/cogni/asquare/cube/index/CollectionFolder.java
  cube/src/main/java/zone/cogni/asquare/cube/index/InternalIndexingServiceUtils.java
  cube/src/main/java/zone/cogni/asquare/cube/index/StaticIndexIndexingService.java
Labels: enhancement, improvement

#155 improve logging in JsonToModelConversion
  cube/src/main/java/zone/cogni/asquare/cube/convertor/ModelToJsonConversion.java
Labels: improvement

#157 add a difference method for models which works for all typed Literals
  cogni-libs/src/main/java/zone/cogni/libs/jena/utils/JenaUtils.java
  cube/src/main/java/zone/cogni/asquare/cube/convertor/JsonToModelConversion.java
Labels: enhancement
